name: Test & Release Storer Go Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-release:
    runs-on: ubuntu-latest
    name: Test and Release Storer Go Module 
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8070:8000
      minio:
        image: minio/minio:edge-cicd
        ports:
          - 8071:9000
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        options: >-
          --name=minio 
          --health-cmd "curl http://localhost:9000/minio/health/live"
      
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'source'
          fetch-depth: "0"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Unit & Functional tests
        working-directory: ./source
        run: |
          make test
        env:
          DYNAMODB_ENDPOINT: http://localhost:8070
          S3_ENDPOINT: http://localhost:8071

      - name: Verify Version Is Changed
        uses: tj-actions/changed-files@v19
        id: version-changed
        with:
          files: |
             version.go

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      
      - name: Read Current Version
        if: ${{ (steps.version-changed.outputs.any_changed == 'true') && (github.event_name == 'push') }}
        run: |
          grep 'const VERSION' version.go | sed -e 's/const VERSION Version = "\(v[^"]*\)"/STORER_VERSION=\1/' >> $GITHUB_ENV
      
      - name: "Release Tag"
        if: ${{ (steps.version-changed.outputs.any_changed == 'true') && (github.event_name == 'push') }}
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ env.STORER_VERSION }}    
